env:
  global:
  - secure: SbfL9b5G/qWUQ9pk9r+BvU2bfghb4uCofC+sdEU9d9G9Kb+OMYMAucrqJzye2pgHD9lehBrYbo1WckkDU8l7VNNa7J6pJgPRnmgb3yj8cdfh+l5XD+58FxW646eXFgdK7VCTmr8B9Y4E9Tov36B65r4ssRz7AHFJceINRK4ukuLCK0/nR95R9XH59x8nh6qD0wKnhnaMYMZilvJW4ns4qjNVcCsfJBYacNpTjhMeXnxg0/XrLCQdZTbmn9tNpLmsG0imsgg8o2DLo7nxOi2uSKAC9NChjl7cyoDKDWgeSDIv187Rg5wH2xfB0jzHraYc3ZFS/w6zcQmYKzTSQ5a5xc7FKKJoRqinttaPBNb8MuTR59CiWn9Kya/8nI+OjndWI3mHkK6p1N5zkN25E5ge2Jh2ocJdopfh+XURw+i1OEVor/QDGXXWZNcwW2An9/iXLPACL5MdFTF/2e4H1awNhFuUeIKDSd8FWuOQv5MO5t9sU1czHgS4hL/lvmz7iCUvjVbacj7Byja7MjNEbrWy7EVH7dmSG93ONwwQO0J7NWrIZlV1+OT1ca+tG2O2DI78tmL2ol7rIcIm6vG678HAwPalgxiEYcVmWCcXjoDowC9U4RzglwvejnwiK5MqX0d8URsg1+Dxt8GLYWEbqk61mjkfNlxvYT3M0VEBJRwzr7I=
  - secure: nU2/iHLUP9WI9yl58J+FjcIKnCpu2G4w1dMsR2i9uJmYBCFYkxdglG7l2OZNWUtb9Na6jf6MTh9cstwmd9W3voZgS7V0OSeDnhWh+gFeP0YHNNqE/JWfP/MWiwsU25z/08sWZ8lqKc9DcpkXHxcXYbj/VSo3U82M0i61I+0YCA8LcLvWIAj3q9/jiWf0VjDBOsPqKsYAaJiVLq0tbUlgSTOmbfuCqcDGeF1+xNmS88ZN0x9dAuJcKRVohhRd2wJM2vUlKXSwqskNPmhTVpz2Xfj+YDkjOxlA6av6AxYpHxtJezYhm8L0teZjzwSm7wch1FpyBkdS+k57b02KZ5lgT2CIy5fFk50l7wnw8dZz1sf24hOjGpMDxH2imTF1jGUTiDs8GUAfH4VoI28C3C9f1dZTbkZzOCz3gN9r8FbFNiJt64BhhuT+RhY0p2iIn5zV9eC7NgAAIjzUtycbc35qsa9idxxSABJxA0TAZwoshJx4DRaLjQT5KTe+uACveWqkNBSpI5x3jAQ4FS0llIxzgSdQq3K2qFqIR9HFIg4Sz1C5amEQTu11fzIgvUVRhOXmPka22+aG1vc/Zy2K/0wZYGkRm1QCCBuk929kgN9PX7ws/N8WF5vVdQXja/HjIVG4aeeTA2nqau7yFs9pUFc2kXeqTqzIrUY8U5leUQEIc+g=
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_ccacfce999a8_key -iv $encrypted_ccacfce999a8_iv
  -in config.json.enc -out config.json -d
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- echo 'I should write some tests...'
- eval $(aws ecr get-login --region us-west-2)
- docker build -t taco-bot-news:latest -t taco-bot-news:1.0.$TRAVIS_BUILD_NUMBER -t
  "869640726279.dkr.ecr.us-west-2.amazonaws.com/taco-bot-news:latest" .
- docker push "869640726279.dkr.ecr.us-west-2.amazonaws.com/taco-bot-news:latest"
